version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    groups:
      typescript:
        patterns:
          - "typescript"

      node-types:
        patterns:
          - "@types/node"

      node-red-types:
        patterns:
          - "@types/node-red"

      azure:
        patterns:
          - "@azure/*"
          - "azure-iot-*"

      tooling:
        patterns:
          - "cpy-cli"
          - "npm-run-all"
          - "rimraf"
          - "node-red"
  - package-ecosystem: "devcontainers"
    directory: "/"
    multi-ecosystem-group: "infrastructure"
    patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "infrastructure"
    patterns: ["*"]
